import AppSidebar from '@/components/common/AppSidebar'
import Header from '@/components/common/Header'
import { SidebarProvider } from '@/components/ui/sidebar'
import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

const primaryFont = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'RadioStation',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`dark antialiased ${primaryFont.className}`}>
        <SidebarProvider>
          <AppSidebar />
          <div className={`wrapper`}>
            <Header />
            {children}
          </div>
        </SidebarProvider>
      </body>
    </html>
  )
}
